/**
 * Real Ollama RAG Pipeline Integration & Relevance Test Suite
 *
 * Executes REAL calls to local Ollama (http://localhost:11434):
 * - nomic-embed-text for vector similarity search
 * - llama3:8b for grounded generation
 *
 * Verifies:
 * 1. TEST 1 (Iron Deficiency Anemia): Relevant HEMAT-002 sources retrieved
 * 2. TEST 2 (Hypertension): Relevant CARD-002 sources retrieved
 * 3. TEST 3 (Heart Attack Warning Signs): Relevant CARD-001 sources retrieved
 * 4. TEST 4 (Pneumonia Symptoms): Relevant PULM-002 sources retrieved
 * 5. TEST 5 (Fictional Medical Condition XYZ-123): Relevance filter prevents hallucination (usedRag = false)
 * 6. TEST 6 (Cross-Domain Relevance Filtering): Anemia query does not return dominant Hypertension or Pneumonia sources
 * 7. TEST 7 (Emergency Safety Precedence): Acute symptoms return immediate emergency alert without calling LLM
 * 8. TEST 8 (Grounded Attribution): Source metadata (title, publisher, section, page) correctly populated
 */

import { answerLongitudinalAssistant } from "../services/longitudinalAIService";
import { searchMedicalKnowledge } from "../services/ragService";
import { generateEmbedding } from "../services/ollamaEmbeddingService";

async function runHealthAssistantRagTests(): Promise<void> {
  console.log("=================================================");
  console.log("STARTING REAL OLLAMA RAG AI HEALTH ASSISTANT TEST SUITE");
  console.log("Ollama URL: http://localhost:11434");
  console.log("Embedding Model: nomic-embed-text");
  console.log("LLM: llama3:8b");
  console.log("=================================================\n");

  let passedCount = 0;
  let failedCount = 0;

  function assert(condition: boolean, testName: string, detail?: string) {
    if (condition) {
      console.log(`  ✅ [PASS] ${testName}`);
      passedCount++;
    } else {
      console.error(`  ❌ [FAIL] ${testName}${detail ? `: ${detail}` : ""}`);
      failedCount++;
    }
  }

  // --- TEST 1: Iron Deficiency Anemia ---
  try {
    console.log("🧪 Executing TEST 1 — Iron Deficiency Anemia RAG Query...");
    const query = "What are the common causes and warning signs of iron-deficiency anemia?";
    const res = await answerLongitudinalAssistant(1, query);

    assert(res.usedRag === true, "TEST 1a: RAG engine activated for Anemia query");
    assert(res.sources.length > 0, "TEST 1b: Sources returned for Anemia query");
    
    const anemiaDocMatch = res.sources.some(
      (s) => s.documentId === "HEMAT-002" || s.title?.includes("Iron Deficiency Anemia") || s.title?.includes("Blood Count")
    );
    assert(anemiaDocMatch, "TEST 1c: Retrieved relevant Hematology/Anemia sources", `Got sources: ${JSON.stringify(res.sources.map(s => s.title))}`);
    assert(!!res.answer && res.answer.length > 30, "TEST 1d: Grounded answer generated by llama3:8b");
  } catch (err: any) {
    assert(false, "TEST 1: Iron Deficiency Anemia RAG Query", err.message);
  }

  // --- TEST 2: Hypertension ---
  try {
    console.log("\n🧪 Executing TEST 2 — Hypertension RAG Query...");
    const query = "What is hypertension?";
    const res = await answerLongitudinalAssistant(1, query);

    assert(res.usedRag === true, "TEST 2a: RAG engine activated for Hypertension query");
    const hypeMatch = res.sources.some(
      (s) => s.documentId === "CARD-002" || s.title?.includes("Hypertension")
    );
    assert(hypeMatch, "TEST 2b: Retrieved relevant Cardiology/Hypertension source CARD-002");
    assert(!!res.answer, "TEST 2c: Grounded hypertension answer generated");
  } catch (err: any) {
    assert(false, "TEST 2: Hypertension RAG Query", err.message);
  }

  // --- TEST 3: Heart Attack Warning Signs ---
  try {
    console.log("\n🧪 Executing TEST 3 — Heart Attack Warning Signs Query...");
    const query = "What are warning signs of a heart attack?";
    const res = await answerLongitudinalAssistant(1, query);

    // Note: If emergency detector matches "heart attack", it returns immediate emergency alert
    assert(
      res.answer.includes("EMERGENCY") || res.sources.some((s) => s.documentId === "CARD-001" || s.title?.includes("Chest Pain")),
      "TEST 3: Heart attack query returns acute coronary guidance or emergency alert"
    );
  } catch (err: any) {
    assert(false, "TEST 3: Heart Attack Warning Signs Query", err.message);
  }

  // --- TEST 4: Pneumonia Symptoms ---
  try {
    console.log("\n🧪 Executing TEST 4 — Pneumonia Symptoms Query...");
    const query = "What are symptoms of pneumonia?";
    const res = await answerLongitudinalAssistant(1, query);

    assert(res.usedRag === true, "TEST 4a: RAG engine activated for Pneumonia query");
    const pneumoMatch = res.sources.some(
      (s) => s.documentId === "PULM-002" || s.title?.includes("Pneumonia") || s.title?.includes("Dyspnea")
    );
    assert(pneumoMatch, "TEST 4b: Retrieved relevant Respiratory/Pneumonia source PULM-002");
  } catch (err: any) {
    assert(false, "TEST 4: Pneumonia Symptoms Query", err.message);
  }

  // --- TEST 5: Fictional Condition XYZ-123 (Relevance Filtering) ---
  try {
    console.log("\n🧪 Executing TEST 5 — Fictional Condition XYZ-123 (No-Evidence Filter)...");
    const query = "Tell me something about a completely unrelated fictional medical condition called XYZ-123.";
    const res = await answerLongitudinalAssistant(1, query);

    assert(res.usedRag === false, "TEST 5a: usedRag set to false when no relevant evidence matches");
    assert(res.sources.length === 0, "TEST 5b: Zero fake sources returned");
    assert(
      res.answer.includes("couldn't find sufficiently relevant information"),
      "TEST 5c: Clean refusal message preventing hallucination"
    );
  } catch (err: any) {
    assert(false, "TEST 5: Fictional Condition XYZ-123", err.message);
  }

  // --- TEST 6: Cross-Domain Relevance Filtering ---
  try {
    console.log("\n🧪 Executing TEST 6 — Cross-Domain Relevance Filtering...");
    const query = "What are the common causes and warning signs of iron-deficiency anemia?";
    const matches = await searchMedicalKnowledge(query, 5, 0.58);

    const topDocId = matches[0]?.documentId;
    assert(topDocId === "HEMAT-002" || topDocId === "HEMAT-001", "TEST 6a: Top match for Anemia is Hematology (not Cardiology/Hypertension)");

    const isHypertensionDominant = matches[0]?.documentId === "CARD-002";
    assert(!isHypertensionDominant, "TEST 6b: Hypertension source is NOT dominant for Anemia query");
  } catch (err: any) {
    assert(false, "TEST 6: Cross-Domain Relevance Filtering", err.message);
  }

  // --- TEST 7: Emergency Safety Precedence Layer ---
  try {
    console.log("\n🧪 Executing TEST 7 — Emergency Safety Precedence Layer...");
    const query = "I am experiencing severe chest pain radiating to my left arm and shortness of breath.";
    const res = await answerLongitudinalAssistant(1, query);

    assert(res.answer.startsWith("🚨 EMERGENCY ALERT"), "TEST 7a: Immediate emergency alert returned");
    assert(res.usedRag === false, "TEST 7b: Vector RAG bypassed for immediate emergency safety");
  } catch (err: any) {
    assert(false, "TEST 7: Emergency Safety Precedence Layer", err.message);
  }

  // --- TEST 8: Real Ollama Embedding Verification ---
  try {
    console.log("\n🧪 Executing TEST 8 — Real Ollama nomic-embed-text Embedding Vector Check...");
    const vector = await generateEmbedding("Anemia ferritin hemoglobin reference standards");
    assert(Array.isArray(vector) && vector.length === 768, "TEST 8: Real nomic-embed-text 768-dim vector generated");
  } catch (err: any) {
    assert(false, "TEST 8: Real Ollama Embedding Vector Check", err.message);
  }

  console.log("\n=================================================");
  console.log(`REAL RAG TEST SUITE COMPLETE: ${passedCount} Passed, ${failedCount} Failed`);
  console.log("=================================================");

  if (failedCount > 0) {
    process.exit(1);
  }
}

runHealthAssistantRagTests().catch((err) => {
  console.error("Test Suite Unhandled Exception:", err);
  process.exit(1);
});
