import { Link } from "wouter";
import { ArrowLeft, FileCheck, AlertTriangle, Stethoscope, Scale, PhoneCall } from "lucide-react";
import { Button } from "@/components/ui/button";

const basePath = import.meta.env.BASE_URL.replace(/\/$/, "");

export function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 flex flex-col font-sans">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-40">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link href="/">
              <Button variant="ghost" size="sm" className="gap-2 text-slate-600 hover:text-slate-900">
                <ArrowLeft className="h-4 w-4" /> Back to Home
              </Button>
            </Link>
          </div>
          <div className="flex items-center gap-2">
            <img src={`${basePath}/logo.png`} alt="ArogyaGenie Logo" className="h-7 w-7 object-contain" />
            <span className="font-bold text-lg text-primary">ArogyaGenie</span>
          </div>
        </div>
      </header>

      {/* Hero Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-blue-900 text-white py-12 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/20 text-blue-300 text-xs font-medium border border-blue-400/30">
            <Scale className="h-3.5 w-3.5" /> User Agreement & Clinical Disclaimers
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">Terms of Service</h1>
          <p className="text-slate-300 text-sm sm:text-base max-w-2xl">
            Please read these terms carefully before using the ArogyaGenie platform, scheduling appointments, or utilizing our AI assistant.
          </p>
          <p className="text-xs text-slate-400">Effective Date: January 1, 2026 | Last Updated: August 2026</p>
        </div>
      </div>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-10 space-y-8">
        {/* Emergency Alert Banner */}
        <div className="bg-red-50 border border-red-200 rounded-2xl p-5 flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between text-red-900">
          <div className="flex gap-3 items-center">
            <div className="h-10 w-10 rounded-xl bg-red-100 flex items-center justify-center text-red-600 flex-shrink-0">
              <AlertTriangle className="h-6 w-6" />
            </div>
            <div>
              <h3 className="font-bold text-sm sm:text-base">Medical Emergency Notice</h3>
              <p className="text-xs sm:text-sm text-red-700">ArogyaGenie is NOT a substitute for emergency medical care. In case of acute chest pain, severe shortness of breath, or trauma, call emergency services immediately.</p>
            </div>
          </div>
          <div className="flex gap-2">
            <a href="tel:112" className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg text-xs font-semibold shadow-sm">
              <PhoneCall className="h-3.5 w-3.5" /> Call 112
            </a>
            <a href="tel:108" className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-red-800 hover:bg-red-900 text-white rounded-lg text-xs font-semibold shadow-sm">
              Ambulance 108
            </a>
          </div>
        </div>

        <section className="bg-white p-6 sm:p-8 rounded-2xl border border-slate-200 shadow-sm space-y-6 text-sm sm:text-base leading-relaxed text-slate-700">
          <div className="space-y-3">
            <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
              <Stethoscope className="h-5 w-5 text-primary" /> 1. Telemedicine & Clinical Disclaimer
            </h2>
            <p>
              ArogyaGenie facilitates communication between registered patients and certified healthcare providers (Doctors, Diagnostic Centers, and Pharmacies).
            </p>
            <ul className="list-disc pl-6 space-y-1.5 text-sm text-slate-600">
              <li><strong>Doctor-Patient Relationship:</strong> Booking an appointment or chatting with our AI health companion does not establish a binding physician-patient relationship until an active, verified doctor consultation takes place.</li>
              <li><strong>AI Health Companion:</strong> Insights generated by the AarogyaBot AI and symptom assessment engine are informational and educational tools based on medical reference guidelines. They do not constitute a definitive medical diagnosis.</li>
              <li><strong>Prescription Validity:</strong> Medicine orders require a valid, verified digital or physical prescription issued by a registered medical practitioner.</li>
            </ul>
          </div>

          <div className="space-y-3 pt-4 border-t border-slate-100">
            <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
              <FileCheck className="h-5 w-5 text-primary" /> 2. User Responsibilities & Account Security
            </h2>
            <ul className="list-disc pl-6 space-y-1.5 text-sm text-slate-600">
              <li>You agree to provide accurate, complete information regarding your medical history, current symptoms, allergies, and contact details.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials and one-time passcodes (OTP).</li>
              <li>Healthcare providers on the platform are required to maintain active state medical licenses and comply with the Telemedicine Practice Guidelines issued by the Ministry of Health and Family Welfare (MoHFW), India.</li>
            </ul>
          </div>

          <div className="space-y-3 pt-4 border-t border-slate-100">
            <h2 className="text-xl font-bold text-slate-900">3. Cancellation, Refunds & Appointments</h2>
            <p className="text-sm text-slate-600">
              Appointment scheduling, doctor consultation fees, and diagnostic package cancellations are subject to individual provider policies as displayed during the booking confirmation checkout.
            </p>
          </div>

          <div className="space-y-3 pt-4 border-t border-slate-100">
            <h2 className="text-xl font-bold text-slate-900">4. Governing Law & Dispute Resolution</h2>
            <p className="text-sm text-slate-600">
              These terms are governed by the laws of India. Any disputes arising in connection with the platform shall be subject to the exclusive jurisdiction of the competent courts in India.
            </p>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 py-6 px-4 text-center text-xs border-t border-slate-800 mt-auto">
        <p>© {new Date().getFullYear()} ArogyaGenie HealthTech. All rights reserved.</p>
      </footer>
    </div>
  );
}
export default TermsOfService;
